### ISSUE TITLE
Rotation student checklist

### ISSUE THREAD

**Issue by ctb** [dib-lab/dib-lab#81]
- [ ] sign up for lab list
- [ ] point at slack channel
- [ ] point at lab calendar/regular lab events

Activities:
- [ ] start with PR on khmer
